# Generated by Django 3.1.3 on 2020-11-21 14:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('resumo', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('imagem', models.ImageField(blank=True, default='/blog/white_image.jpg', null=True, upload_to='blog')),
                ('data_nasc', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentarios', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('resumo', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('link', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, default='white_image.jpg', upload_to='media')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.user')),
            ],
        ),
    ]
