# Generated by Django 3.1.3 on 2020-11-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201121_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
