# Generated by Django 3.1.3 on 2020-11-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_categoria_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comentarios',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
